services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
    depends_on:
      database:
       condition: service_healthy
  frontend:
    build:
      context: ./frontend
      args:
        - API_URL=http://localhost:8000/api/
    ports:
      - 3000:80
  database:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 10s