# Generated by Django 5.0.3 on 2024-03-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_created_by_ticket_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
