# Generated by Django 5.0.3 on 2024-04-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticketreply_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketreply',
            old_name='ticket',
            new_name='tickets',
        ),
    ]
