# Generated by Django 5.0.3 on 2024-04-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_ticket_ticketreply_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketreply',
            old_name='tickets',
            new_name='ticket',
        ),
    ]
